Fix code to work with Python 3.8 and 3.9
* env python2 → python3
* Fixed problems with concatenation of str and bytes
* Removed \x00 from font names, so that the 'make check' tests pass
* Improved Makefile to work without {} that lead to 'file not found'
  in some situations
* 'make check' passes for Python 3.8 and 3.9

This is the error before the fix:

$ python3.8 ./doc-dump.py test/doc/fonts.doc
Traceback (most recent call last):
  File "./doc-dump.py", line 43, in <module>
    main(sys.argv)
  File "./doc-dump.py", line 39, in main
    dumper.dump()
  File "./doc-dump.py", line 23, in dump
    strm = docstream.createDOCFile(file.read(), self.params)
  File "mso-dumper/msodumper/docstream.py", line 131, in createDOCFile
    return GsfDOCFile(chars, params, gsf)
  File "mso-dumper/msodumper/docstream.py", line 75, in __init__
    DOCFile.__init__(self, chars, params)
  File "mso-dumper/msodumper/docstream.py", line 29, in __init__
    self.initWW8()
  File "mso-dumper/msodumper/docstream.py", line 107, in initWW8
    childData += ctypes.string_at(self.gsf.gsf_input_read(child, bufSize, None), bufSize)
TypeError: can only concatenate str (not "bytes") to str

Change-Id: I804e2973b283a435a03ab55b258b7db5b9372693
Reviewed-on: https://gerrit.libreoffice.org/c/mso-dumper/+/121617
Tested-by: Miklos Vajna <vmiklos@collabora.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>