Fix doc-dump.py problem with dumping binary data
I was getting this error when invoking:

    ./doc-dump.py test/doc/pass/tdf141049.doc

...
  File "mso-dumper/msodumper/msodraw.py", line 40, in inflate
    return textwrap.fill(base64.b64encode(zlib.decompress(bytes)), width=160)
  File "/usr/lib/python3.8/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/usr/lib/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.8/textwrap.py", line 351, in wrap
    chunks = self._split_chunks(text)
  File "/usr/lib/python3.8/textwrap.py", line 337, in _split_chunks
    text = self._munge_whitespace(text)
  File "/usr/lib/python3.8/textwrap.py", line 156, in _munge_whitespace
    text = text.translate(self.unicode_whitespace_trans)
TypeError: a bytes-like object is required, not 'dict'

To check:

    cd test/doc && ./test.py

Or simply run all the tests:

    make check

The test fails without this fix in place.

Change-Id: I1573ed0568ceb46c01847008fad0c49d1142420c