Fix emf-dump to work with Python 3.8
Using update() method instead of + operator for dict items

After running with

    /opt/libreoffice7.2/program/python ./emf-dump.py test.emf

This error was shown:

Traceback (most recent call last):
  File "./emf-dump.py", line 8, in <module>
    from msodumper import emfrecord
  File "msodumper/emfrecord.py", line 139, in <module>
    HatchStyle = dict(wmfrecord.HatchStyle.items() + EmfHatchStyle.items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

Also, in Python 3, the default encoding is utf-8, so using
sys.setdefaultencoding("utf-8") is not needed/encouraged.